background = 0xff131313
base = 0xff131313
text = 0xffe2e2e2
alternate_base = 0xff474747
bright_text = 0xffc6c6c6
accent = 0xffa1c9ff
accent_secondary = 0xffbbc7db

h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10

icon_theme = 
font_family = Sans Serif
font_family_monospace = monospace

rounding_large = 10
rounding_small = 5
